<h1><center>PORTADA</h1>

<h4>
<center>
    <h4>Ejercicio 2: Limpieza y procesamiento de datos.</h4>
<h4>
Curso: Programación para el Analisis de datos<br>
Tarea: Datos en línea y tipos de datos.<br>
Presentado por: Wagner Alonso Fernández Villalobos<br>
Grupo: 203008069_14<br>
Código: 203008069A_1702<br>
Presentado a: Jose Laureano Cruz Cardozo<br>
Universidad: Universidad Nacional Abierta y a Distancia – UNAD<br>
Fecha: 13/06/2024<br>
<h/4>
</center>

<h1><center>INTRODUCCIÓN</h1>

<p style="text-align: justify;">En un mundo impulsado por datos, la capacidad de extraer información útil de grandes conjuntos de datos es intrínseco para el éxito en diversos campos, sin embargo, antes de que los datos puedan ser analizados de manera efectiva, a menudo es necesario prepararlos mediante un proceso meticuloso de limpieza y procesamiento; este trabajo tiene como objetivo aplicar los conceptos fundamentales y las técnicas esenciales involucradas en la limpieza y el procesamiento de datos, sentando las bases para un análisis preciso y confiable.</p>

<p style="text-align: justify;">En las siguientes celdas, se procede con aplicar funciones concernientes a procesar tipos de datos con el lenguaje de programación Python, convertirlos en minusculas y mayusculas, creación de columnas e imputación de datos.</p>

<h1><center>DESARROLLO</h1>

Cargue de nuevo los datos del Ejercicio 1, pero genere un DataFrame llamado df, solamente con las columnas:

* type
* mass_kg
* year_built
* home_port
* name

Siguiendo las funciones mostradas en las referencias bibliográficas, desarrolle las siguientes tareas en el DataFrame generado
anteriormente:

#### 1. Revisando datos faltantes:

* Determine cuantos datos faltantes hay en la variable mass_kg del mediante value_counts()

* Crea un DataFrame df1 removiendo las filas que tienen algunos datos faltantes. Por otro lado crea un DataFrame df2 removiendo
las filas que tienen todos los datos faltantes. Compáralos y comenta los resultados.

* En el DataFrame df completa los datos faltantes por los siguientes tres métodos (muestra y comenta los resultados):

* Completar datos faltantes con el número 0.

* Completar por método de propagación hacia adelante.

* Completar los valores faltantes con el promedio de la columna.

Se procede con desarrollar las acciones pertinentes a extraer la información y desarrollar el punto conforme a lo estipulado en el material de Idris (2014); es importante resaltar que este procedimiento que se mostrará en la siguiente celda de código, es una API "interfaz de programación de aplicaciones" por sus siglas en inglés, donde se extrae la información de una pagina web Roldán (2019, p.72)

In [1]:
import requests as rq# importar la librería request

data = rq.request('GET','https://api.spacexdata.com/v4/ships')#obtención del datos a través del método GET

data

to_json = data.json()# conversión de los datos extraidos a formato diccionario

to_json

[{'last_ais_update': None,
  'legacy_id': 'AMERICANCHAMPION',
  'model': None,
  'type': 'Tug',
  'roles': ['Support Ship', 'Barge Tug'],
  'imo': 7434016,
  'mmsi': 367020820,
  'abs': 571252,
  'class': 7604342,
  'mass_kg': 266712,
  'mass_lbs': 588000,
  'year_built': 1976,
  'home_port': 'Port of Los Angeles',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:434663/mmsi:367020820/imo:7434016/vessel:AMERICAN_CHAMPION',
  'image': 'https://i.imgur.com/woCxpkj.jpg',
  'name': 'American Champion',
  'active': False,
  'launches': ['5eb87cdeffd86e000604b330', '5eb87cdfffd86e000604b331'],
  'id': '5ea6ed2d080df4000697c901'},
 {'last_ais_update': None,
  'legacy_id': 'AMERICANISLANDER',
  'model': None,
  'type': 'Cargo',
  'roles': ['Dragon Recovery'],
  'imo': None,
  'mmsi': 367035570,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': None,
  'home_port': 'Port of Los Angeles',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:435112/mmsi:367035570/imo:0/vessel:AMERICAN_ISLANDER',
  'image': 'https://i.imgur.com/jmj8Sh2.jpg',
  'name': 'American Islander',
  'active': False,
  'launches': ['5eb87ce0ffd86e000604b332',
   '5eb87ce1ffd86e000604b333',
   '5eb87ce4ffd86e000604b337',
   '5eb87ce7ffd86e000604b33b'],
  'id': '5ea6ed2d080df4000697c902'},
 {'last_ais_update': None,
  'legacy_id': 'AMERICANSPIRIT',
  'model': None,
  'type': 'Cargo',
  'roles': ['Support Ship'],
  'imo': None,
  'mmsi': None,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': None,
  'home_port': 'Port of Los Angeles',
  'status': None,
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': None,
  'image': None,
  'name': 'American Spirit',
  'active': False,
  'launches': ['5eb87ce1ffd86e000604b334'],
  'id': '5ea6ed2d080df4000697c903'},
 {'last_ais_update': None,
  'legacy_id': 'ASOG',
  'model': None,
  'type': 'Barge',
  'roles': ['ASDS barge'],
  'imo': None,
  'mmsi': None,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': 2021,
  'home_port': 'Port Canaveral',
  'status': None,
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': None,
  'image': None,
  'name': 'A Shortfall of Gravitas',
  'active': True,
  'launches': ['5fe3b11eb3467846b324216c',
   '5fe3b15eb3467846b324216d',
   '6161c94c6db1a92bfba85349',
   '61d5eca1f88e4c5fc91f1eb7',
   '61e048bbbe8d8b66799018d0'],
  'id': '5ea6ed2d080df4000697c904'},
 {'last_ais_update': None,
  'legacy_id': 'BETTYRGAMBARELLA',
  'model': None,
  'type': 'Tug',
  'roles': ['ASDS Tug'],
  'imo': 7517478,
  'mmsi': 368000890,
  'abs': 562590,
  'class': 7427463,
  'mass_kg': 202302,
  'mass_lbs': 446000,
  'year_built': 1974,
  'home_port': 'Port of Los Angeles',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:1190856/mmsi:368000890/imo:7517478/vessel:BETTY_R_GAMBARELLA',
  'image': 'https://i.imgur.com/ngYgFnn.jpg',
  'name': 'Betty R Gambarella',
  'active': False,
  'launches': ['5eb87d08ffd86e000604b357', '5eb87d0affd86e000604b359'],
  'id': '5ea6ed2e080df4000697c905'},
 {'last_ais_update': None,
  'legacy_id': 'ELSBETH3',
  'model': None,
  'type': 'Tug',
  'roles': ['ASDS Tug'],
  'imo': 8983375,
  'mmsi': 367017460,
  'abs': None,
  'class': None,
  'mass_kg': 273063,
  'mass_lbs': 602000,
  'year_built': 1999,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:434560/mmsi:367017460/imo:8983375/vessel:ELSBETH_III',
  'image': 'https://i.imgur.com/1s5DUbJ.jpg',
  'name': 'Elsbeth III',
  'active': False,
  'launches': ['5eb87ce8ffd86e000604b33c',
   '5eb87ceaffd86e000604b33d',
   '5eb87cecffd86e000604b33f',
   '5eb87ceeffd86e000604b341',
   '5eb87cf2ffd86e000604b344',
   '5eb87cf3ffd86e000604b345',
   '5eb87cf5ffd86e000604b346',
   '5eb87cf6ffd86e000604b347',
   '5eb87cf8ffd86e000604b348',
   '5eb87cf9ffd86e000604b349',
   '5eb87cfaffd86e000604b34a',
   '5eb87d00ffd86e000604b34f',
   '5eb87d04ffd86e000604b353',
   '5eb87d09ffd86e000604b358'],
  'id': '5ea6ed2e080df4000697c906'},
 {'last_ais_update': None,
  'legacy_id': 'GOMSCHIEF',
  'model': None,
  'type': 'High Speed Craft',
  'roles': ['Fairing Recovery'],
  'imo': 9744453,
  'mmsi': 338035000,
  'abs': 1247527,
  'class': 14245747,
  'mass_kg': 449964,
  'mass_lbs': 992000,
  'year_built': 2014,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:5126789/mmsi:338035000/imo:9744453/vessel:GO_MS_CHIEF',
  'image': 'https://imgur.com/NHsx95l.jpg',
  'name': 'GO Ms Chief',
  'active': False,
  'launches': ['5eb87d3bffd86e000604b37f',
   '5eb87d3fffd86e000604b382',
   '5eb87d41ffd86e000604b383',
   '5eb87d44ffd86e000604b386',
   '5eb87d45ffd86e000604b387',
   '5eb87d46ffd86e000604b389',
   '5eb87d50ffd86e000604b394',
   '5ed9819a1f30554030d45c29',
   '5ed981d91f30554030d45c2a',
   '5eb87d47ffd86e000604b38a',
   '5ef6a2090059c33cee4a828b',
   '5ef6a2bf0059c33cee4a828c',
   '5ef6a2e70059c33cee4a8293',
   '5eb87d4cffd86e000604b38d',
   '5fb95b3f3a88ae63c954603c',
   '5eb87d4fffd86e000604b393',
   '5fbfecce54ceb10a5664c80a',
   '5fd386aa7faea57d297c86c1',
   '5ff6554f9257f579ee3a6c5f'],
  'id': '5ea6ed2e080df4000697c907'},
 {'last_ais_update': None,
  'legacy_id': 'GOMSTREE',
  'model': None,
  'type': 'High Speed Craft',
  'roles': ['Fairing Recovery'],
  'imo': 9744465,
  'mmsi': 368059550,
  'abs': 1249191,
  'class': 15252765,
  'mass_kg': 449964,
  'mass_lbs': 992000,
  'year_built': 2015,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:3439091/mmsi:368099550/imo:9744465/vessel:GO_MS_TREE',
  'image': 'https://i.imgur.com/MtEgYbY.jpg',
  'name': 'GO Ms Tree',
  'active': False,
  'launches': ['5eb87d0dffd86e000604b35b',
   '5eb87d0fffd86e000604b35d',
   '5eb87d14ffd86e000604b361',
   '5eb87d16ffd86e000604b363',
   '5eb87d1affd86e000604b367',
   '5eb87d1fffd86e000604b36b',
   '5eb87d25ffd86e000604b370',
   '5eb87d35ffd86e000604b37a',
   '5eb87d37ffd86e000604b37c',
   '5eb87d39ffd86e000604b37d',
   '5eb87d3bffd86e000604b37f',
   '5eb87d3cffd86e000604b380',
   '5eb87d3fffd86e000604b382',
   '5eb87d41ffd86e000604b383',
   '5eb87d44ffd86e000604b386',
   '5eb87d45ffd86e000604b387',
   '5eb87d46ffd86e000604b389',
   '5eb87d50ffd86e000604b394',
   '5ed9819a1f30554030d45c29',
   '5ed981d91f30554030d45c2a',
   '5ef6a1e90059c33cee4a828a',
   '5ef6a2090059c33cee4a828b',
   '5ef6a2bf0059c33cee4a828c',
   '5ef6a2e70059c33cee4a8293',
   '5f8399fb818d8b59f5740d43',
   '5eb87d4fffd86e000604b393',
   '5fbfecce54ceb10a5664c80a',
   '5fd386aa7faea57d297c86c1',
   '5ff6554f9257f579ee3a6c5f'],
  'id': '5ea6ed2e080df4000697c908'},
 {'last_ais_update': None,
  'legacy_id': 'SHANNON',
  'model': None,
  'type': 'Cargo',
  'roles': ['Support Ship', 'Fairing Recovery'],
  'imo': 9566887,
  'mmsi': 367550000,
  'abs': 1221524,
  'class': 9204358,
  'mass_kg': 451778,
  'mass_lbs': 996000,
  'year_built': 2009,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:452540/mmsi:367550000/imo:9566887/vessel:GO_NAVIGATOR',
  'image': 'https://i.imgur.com/MjNWzhO.jpg',
  'name': 'Shannon',
  'active': True,
  'launches': ['5eb87d2dffd86e000604b376',
   '5eb87d30ffd86e000604b378',
   '5eb87d35ffd86e000604b37a',
   '5eb87d37ffd86e000604b37c',
   '5eb87d39ffd86e000604b37d',
   '5eb87d3cffd86e000604b380',
   '5eb87d46ffd86e000604b388',
   '5eb87d4dffd86e000604b38e',
   '600f9a718f798e2a4d5f979d',
   '600f9a8d8f798e2a4d5f979e',
   '5fe3af58b3467846b324215f',
   '6079bd399a06446e8c61bf77',
   '5fe3af6db3467846b3242160',
   '5fe3b15eb3467846b324216d',
   '61eefaa89eb1064137a1bd73'],
  'id': '5ea6ed2e080df4000697c909'},
 {'last_ais_update': None,
  'legacy_id': 'GOPURSUIT',
  'model': None,
  'type': 'Cargo',
  'roles': ['Support Ship', 'Fairing Recovery'],
  'imo': 9458884,
  'mmsi': 367191410,
  'abs': 1201189,
  'class': 7174230,
  'mass_kg': 502999,
  'mass_lbs': 1108925,
  'year_built': 2007,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:439594/mmsi:367191410/imo:9458884/vessel:GO_PURSUIT',
  'image': 'https://i.imgur.com/5w1ZWre.jpg',
  'name': 'GO Pursuit',
  'active': False,
  'launches': ['5eb87d18ffd86e000604b365',
   '5eb87d19ffd86e000604b366',
   '5eb87d1bffd86e000604b368',
   '5eb87d1effd86e000604b36a'],
  'id': '5ea6ed2e080df4000697c90a'},
 {'last_ais_update': None,
  'legacy_id': 'GOQUEST',
  'model': None,
  'type': 'Cargo',
  'roles': ['Support Ship'],
  'imo': 1155515,
  'mmsi': 367564890,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': 2014,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:450521/mmsi:367564890/imo:1155515/vessel:GO_QUEST',
  'image': 'https://i.imgur.com/ABXtHKa.jpg',
  'name': 'GO Quest',
  'active': True,
  'launches': ['5eb87ce8ffd86e000604b33c',
   '5eb87ceaffd86e000604b33d',
   '5eb87cecffd86e000604b33f',
   '5eb87ceeffd86e000604b341',
   '5eb87cf2ffd86e000604b344',
   '5eb87cf3ffd86e000604b345',
   '5eb87cf5ffd86e000604b346',
   '5eb87cf6ffd86e000604b347',
   '5eb87cf8ffd86e000604b348',
   '5eb87cf9ffd86e000604b349',
   '5eb87cfaffd86e000604b34a',
   '5eb87d00ffd86e000604b34f',
   '5eb87d04ffd86e000604b353',
   '5eb87d09ffd86e000604b358',
   '5eb87d0cffd86e000604b35a',
   '5eb87d11ffd86e000604b35f',
   '5eb87d18ffd86e000604b365',
   '5eb87d19ffd86e000604b366',
   '5eb87d1effd86e000604b36a',
   '5eb87d22ffd86e000604b36d',
   '5eb87d26ffd86e000604b371',
   '5eb87d2dffd86e000604b376',
   '5eb87d2effd86e000604b377',
   '5eb87d30ffd86e000604b378',
   '5eb87d35ffd86e000604b37a',
   '5eb87d3cffd86e000604b380',
   '5eb87d3fffd86e000604b382',
   '5eb87d41ffd86e000604b383',
   '5eb87d46ffd86e000604b388',
   '5eb87d46ffd86e000604b389',
   '5eb87d50ffd86e000604b394',
   '5ed981d91f30554030d45c2a',
   '5ef6a1e90059c33cee4a828a',
   '5ef6a2090059c33cee4a828b',
   '5ef6a2bf0059c33cee4a828c',
   '5ef6a2e70059c33cee4a8293',
   '5eb87d4dffd86e000604b38e',
   '5fb95b3f3a88ae63c954603c',
   '5eb87d4effd86e000604b391',
   '5fbfecce54ceb10a5664c80a',
   '5ff6554f9257f579ee3a6c5f',
   '60428aafc041c16716f73cd7',
   '60428ac4c041c16716f73cd8',
   '605b4b95aa5433645e37d041',
   '6079bd399a06446e8c61bf77',
   '5fe3af84b3467846b3242161',
   '5fe3af6db3467846b3242160',
   '5fe3b107b3467846b324216b',
   '61bba806437241381bf7061e'],
  'id': '5ea6ed2f080df4000697c90b'},
 {'last_ais_update': None,
  'legacy_id': 'MEGAN',
  'model': None,
  'type': 'Cargo',
  'roles': ['Support Ship', 'Fairing Recovery'],
  'imo': 9591648,
  'mmsi': 366584000,
  'abs': 1226876,
  'class': 10204360,
  'mass_kg': 450870,
  'mass_lbs': 994000,
  'year_built': 2010,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:426008/mmsi:366584000/imo:9591648/vessel:GO_SEARCHER',
  'image': 'https://i.imgur.com/X4YQJZf.jpg',
  'name': 'Megan',
  'active': True,
  'launches': ['5eb87ce8ffd86e000604b33c',
   '5eb87ceaffd86e000604b33d',
   '5eb87cecffd86e000604b33f',
   '5eb87ceeffd86e000604b341',
   '5eb87cf2ffd86e000604b344',
   '5eb87cf3ffd86e000604b345',
   '5eb87cf5ffd86e000604b346',
   '5eb87cf6ffd86e000604b347',
   '5eb87cf8ffd86e000604b348',
   '5eb87cf9ffd86e000604b349',
   '5eb87cfaffd86e000604b34a',
   '5eb87d00ffd86e000604b34f',
   '5eb87d01ffd86e000604b350',
   '5eb87d04ffd86e000604b353',
   '5eb87d13ffd86e000604b360',
   '5eb87d2dffd86e000604b376',
   '5eb87d30ffd86e000604b378',
   '5eb87d3dffd86e000604b381',
   '5eb87d46ffd86e000604b388',
   '5eb87d4dffd86e000604b38e',
   '5fb95b3f3a88ae63c954603c',
   '5eb87d4bffd86e000604b38c',
   '5f8399fb818d8b59f5740d43',
   '5fd386aa7faea57d297c86c1',
   '600f9a718f798e2a4d5f979d',
   '600f9a8d8f798e2a4d5f979e',
   '6079bd399a06446e8c61bf77',
   '5fe3b15eb3467846b324216d'],
  'id': '5ea6ed2f080df4000697c90c'},
 {'last_ais_update': None,
  'legacy_id': 'HAWK',
  'model': None,
  'type': 'Tug',
  'roles': ['ASDS Tug'],
  'imo': 9103295,
  'mmsi': 366943250,
  'abs': 1033239,
  'class': 9523438,
  'mass_kg': 508023,
  'mass_lbs': 1120000,
  'year_built': 1995,
  'home_port': 'Port Canaveral',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:430027/mmsi:366943250/imo:9103295/vessel:HAWK',
  'image': 'https://i.imgur.com/hGWWupT.jpg',
  'name': 'HAWK',
  'active': False,
  'launches': ['5eb87d0cffd86e000604b35a',
   '5eb87d0dffd86e000604b35b',
   '5eb87d13ffd86e000604b360',
   '5eb87d18ffd86e000604b365',
   '5eb87d1effd86e000604b36a',
   '5eb87d20ffd86e000604b36c',
   '5eb87d22ffd86e000604b36d',
   '5eb87d24ffd86e000604b36f',
   '5eb87d39ffd86e000604b37d',
   '5eb87d39ffd86e000604b37e',
   '5eb87d3bffd86e000604b37f',
   '5eb87d3cffd86e000604b380',
   '5eb87d3fffd86e000604b382',
   '5eb87d41ffd86e000604b383',
   '5eb87d43ffd86e000604b385',
   '5eb87d46ffd86e000604b388',
   '5fb95b3f3a88ae63c954603c',
   '5eb87d4effd86e000604b391',
   '5eb87d4fffd86e000604b393',
   '5fbfecce54ceb10a5664c80a',
   '5fbfecfe54ceb10a5664c80b',
   '600f9a8d8f798e2a4d5f979e',
   '605b4b6aaa5433645e37d03f'],
  'id': '5ea6ed2f080df4000697c90d'},
 {'last_ais_update': None,
  'legacy_id': 'HOLLYWOOD',
  'model': None,
  'type': 'Tug',
  'roles': ['ASDS Tug'],
  'imo': 8428674,
  'mmsi': 366955620,
  'abs': None,
  'class': None,
  'mass_kg': 320236,
  'mass_lbs': 706000,
  'year_built': 1985,
  'home_port': 'Fort Lauderdale',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:430344/mmsi:367648150/imo:8428674/vessel:CAITLIN',
  'image': 'https://photos.marinetraffic.com/ais/showphoto.aspx?photoid=3406596',
  'name': 'Hollywood',
  'active': True,
  'launches': ['5eb87d2dffd86e000604b376',
   '5eb87d2effd86e000604b377',
   '5eb87d30ffd86e000604b378',
   '5eb87d35ffd86e000604b37a'],
  'id': '5ea6ed2f080df4000697c90e'},
 {'last_ais_update': None,
  'legacy_id': 'JRTI-1',
  'model': 'Marmac 300',
  'type': 'Barge',
  'roles': ['ASDS barge'],
  'imo': None,
  'mmsi': None,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': 2014,
  'home_port': 'Port Canaveral',
  'status': None,
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': None,
  'image': 'https://i.imgur.com/RJPmP8G.jpg',
  'name': 'Just Read The Instructions 1',
  'active': False,
  'launches': ['5eb87ce8ffd86e000604b33c', '5eb87cecffd86e000604b33f'],
  'id': '5ea6ed2f080df4000697c90f'},
 {'last_ais_update': None,
  'legacy_id': 'JRTI-2',
  'model': 'Marmac 303',
  'type': 'Barge',
  'roles': ['ASDS barge'],
  'imo': None,
  'mmsi': None,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': 2015,
  'home_port': 'Port Canaveral',
  'status': None,
  'speed_kn': None,
  'course_deg': None,
  'latitude': 33.7291858,
  'longitude': -118.262015,
  'link': None,
  'image': 'https://i.imgur.com/7VMC0Gn.jpg',
  'name': 'Just Read The Instructions 2',
  'active': True,
  'launches': ['5eb87cf0ffd86e000604b343',
   '5eb87cfdffd86e000604b34c',
   '5eb87d05ffd86e000604b354',
   '5eb87d08ffd86e000604b357',
   '5eb87d0affd86e000604b359',
   '5eb87d1fffd86e000604b36b',
   '5eb87d25ffd86e000604b370',
   '5eb87d28ffd86e000604b373',
   '5ef6a2090059c33cee4a828b',
   '5ef6a2e70059c33cee4a8293',
   '5eb87d4dffd86e000604b38e',
   '5eb87d4bffd86e000604b38c',
   '5eb87d4fffd86e000604b393',
   '5fbfecce54ceb10a5664c80a',
   '600f9a718f798e2a4d5f979d',
   '605b4b6aaa5433645e37d03f',
   '5fe3af6db3467846b3242160',
   '5eb87d4effd86e000604b390',
   '607a37565a906a44023e0866',
   '618faad2563d69573ed8ca9d',
   '6161d2006db1a92bfba85356'],
  'id': '5ea6ed2f080df4000697c910'},
 {'last_ais_update': None,
  'legacy_id': 'KELLYC',
  'model': None,
  'type': 'Tug',
  'roles': ['ASDS Tug'],
  'imo': None,
  'mmsi': 367693690,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': None,
  'home_port': 'Port of Los Angeles',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:3718707/mmsi:367693690/imo:0/vessel:KELLY_C',
  'image': None,
  'name': 'Kelly C',
  'active': False,
  'launches': ['5eb87d05ffd86e000604b354'],
  'id': '5ea6ed2f080df4000697c911'},
 {'last_ais_update': None,
  'legacy_id': 'NRCQUEST',
  'model': None,
  'type': 'Cargo',
  'roles': ['Support Ship', 'Dragon Recovery'],
  'imo': 9271195,
  'mmsi': 367486370,
  'abs': 1134613,
  'class': 2115909,
  'mass_kg': 440892,
  'mass_lbs': 972000,
  'year_built': 2002,
  'home_port': 'Port of Los Angeles',
  'status': '',
  'speed_kn': None,
  'course_deg': None,
  'latitude': None,
  'longitude': None,
  'link': 'https://www.marinetraffic.com/en/ais/details/ships/shipid:447294/mmsi:367486370/imo:9271195/vessel:NRC_QUEST',
  'image': 'https://i.imgur.com/GvtuYUN.jpg',
  'name': 'NRC Quest',
  'active': True,
  'launches': ['5eb87ce8ffd86e000604b33c',
   '5eb87cecffd86e000604b33f',
   '5eb87cf0ffd86e000604b343',
   '5eb87cf3ffd86e000604b345',
   '5eb87cf9ffd86e000604b349',
   '5eb87cfdffd86e000604b34c',
   '5eb87cfeffd86e000604b34d',
   '5eb87d03ffd86e000604b352',
   '5eb87d05ffd86e000604b354',
   '5eb87d07ffd86e000604b356',
   '5eb87d0effd86e000604b35c',
   '5eb87d16ffd86e000604b364',
   '5eb87d1cffd86e000604b369',
   '5eb87d1fffd86e000604b36b',
   '5eb87d25ffd86e000604b370',
   '5eb87d28ffd86e000604b373',
   '5fe3b107b3467846b324216b',
   '61bba806437241381bf7061e'],
  'id': '5ea6ed30080df4000697c912'},
 {'last_ais_update': None,
  'legacy_id': 'OCISLY',
  'model': 'Marmac 304',
  'type': 'Barge',
  'roles': ['ASDS barge'],
  'imo': None,
  'mmsi': None,
  'abs': None,
  'class': None,
  'mass_kg': None,
  'mass_lbs': None,
  'year_built': 2015,
  'home_port': 'Port of Los Angeles',
  'status': None,
  'speed_kn': None,
  'course_deg': None,
  'latitude': 33.7291858,
  'longitude': -118.262015,
  'link': None,
  'image': 'https://i.imgur.com/28dCx6G.jpg',
  'name': 'Of Course I Still Love You',
  'active': True,
  'launches': ['5eb87cf2ffd86e000604b344',
   '5eb87cf3ffd86e000604b345',
   '5eb87cf6ffd86e000604b347',
   '5eb87cf8ffd86e000604b348',
   '5eb87cfaffd86e000604b34a',
   '5eb87d00ffd86e000604b34f',
   '5eb87d04ffd86e000604b353',
   '5eb87d0cffd86e000604b35a',
   '5eb87d0dffd86e000604b35b',
   '5eb87d13ffd86e000604b360',
   '5eb87d18ffd86e000604b365',
   '5eb87d19ffd86e000604b366',
   '5eb87d1effd86e000604b36a',
   '5eb87d20ffd86e000604b36c',
   '5eb87d22ffd86e000604b36d',
   '5eb87d24ffd86e000604b36f',
   '5eb87d2affd86e000604b374',
   '5eb87d2bffd86e000604b375',
   '5eb87d2dffd86e000604b376',

<p style="text-align: justify;">En el siguiente código, se utiliza la función pd.DataFrame para crear un dataframe a partir de la lista de diccionarios devuelta por la API de SpaceX, luego se selecciona solo las columnas especíque pide la guia de aprendizaje y evaluación.</p>

In [2]:
import pandas as pd
df = pd.DataFrame(to_json)[['type', 'mass_kg', 'year_built', 'home_port', 'name']]#extracción de las columnas necesarias
df

,type,mass_kg,year_built,home_port,name
0,Tug,266712.0,1976.0,Port of Los Angeles,American Champion
1,Cargo,NaN,NaN,Port of Los Angeles,American Islander
2,Cargo,NaN,NaN,Port of Los Angeles,American Spirit
3,Barge,NaN,2021.0,Port Canaveral,A Shortfall of Gravitas
4,Tug,202302.0,1974.0,Port of Los Angeles,Betty R Gambarella
5,Tug,273063.0,1999.0,Port Canaveral,Elsbeth III
6,High Speed Craft,449964.0,2014.0,Port Canaveral,GO Ms Chief
7,High Speed Craft,449964.0,2015.0,Port Canaveral,GO Ms Tree
8,Cargo,451778.0,2009.0,Port Canaveral,Shannon
9,Cargo,502999.0,2007.0,Port Canaveral,GO Pursuit
10,Cargo,NaN,2014.0,Port Canaveral,GO Quest
11,Cargo,450870.0,2010.0,Port Canaveral,Megan
12,Tug,508023.0,1995.0,Port Canaveral,HAWK
13,Tug,320236.0,1985.0,Fort Lauderdale,Hollywood
14,Barge,NaN,2014.0,Port Canaveral,Just Read The Instructions 1
15,Barge,NaN,2015.0,Port Canaveral,Just Read The Instructions 2
16,Tug,NaN,NaN,Port of Los Angeles,Kelly C
17,Cargo,440892.0,2002.0,Port of Los Angeles,NRC Quest
18,Barge,NaN,2015.0,Port of Los Angeles,Of Course I Still Love You
19,Tug,89811.0,1976.0,Port of Los Angeles,Pacific Freeedom
20,Tug,351080.0,1974.0,Port of Los Angeles,Pacific Warrior
21,Tug,312072.0,1976.0,Port Canaveral,RACHEL
22,Tug,843682.0,1975.0,Port Canaveral,Finn Falgout
23,Tug,741170.0,2003.0,Port Canaveral,Lauren Foss
24,Cargo,2097411.0,2014.0,Port Canaveral,Shelia Bordelon
25,Tug,445428.0,1944.0,Port Canaveral,Mr. Jonah
26,Cargo,4616663.0,2015.0,Port Canaveral,HOS Briarwood
27,Cargo,2719740.0,2009.0,Port Canaveral,Doug
28,Cargo,2719740.0,2009.0,Port Canaveral,Bob

En el caso desglosado anteriormente, se observa la que hay varias columnas con valores faltantes o nulos, que pueden ser imputados, los cuales son representados con la palabra NaN, que son las siglas de Not a Number, que traduciendolo al español es no hay numero. Madhavan (2015)

In [3]:
datos_faltantes = df['mass_kg'].isnull().sum()#revisión de los datos faltantes en la variable "mass_kg"
print("Los datos faltantes que hay en la columna 'mass_kg' es de:",datos_faltantes, 'registros')

Los datos faltantes que hay en la columna 'mass_kg' es de: 8 registros

Se desarrolla el DataFrame "df1", removiendo las filas que tienen algunos datos faltantes, utilizando el método dropna(), consultado en el libro de McKinney(2023), para este caso si como profesionales de datos, deseamos eliminar datos.

In [4]:
df1 = df.dropna(subset=['mass_kg'])

Se desarrolla el DataFrame "df2", removiendo las filas que tienen algunos datos faltantes, utilizando el método dropna()

In [5]:
df2 = df.dropna(how='all')

Se procede con completar los valores faltantes con el promedio de la columna con el metodo fillna Madhavan (2015)

In [6]:
df.fillna(0, inplace=True)# el valor a insertar en los dataframe este 0
df.fillna(method='ffill', inplace=True)#se rellenan los valores faltantes utilizando el método de "forward fill" o "relleno hacia adelante".

C:\Users\WAGNER FERNÁNDEZ\AppData\Local\Temp\ipykernel_16068\4114572768.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)#se rellenan los valores faltantes utilizando el método de "forward fill" o "relleno hacia adelante".

Se procede con la imputación de los datos en columnas en blanco, donde se inserta el numero 0

In [7]:
promedio = df['mass_kg'].mean()# metodo .mean() o el promedio de los datos
df['mass_kg'].fillna(promedio, inplace=True)

C:\Users\WAGNER FERNÁNDEZ\AppData\Local\Temp\ipykernel_16068\1367905038.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mass_kg'].fillna(promedio, inplace=True)

Impresión del DataFrame imputado

In [8]:
df

,type,mass_kg,year_built,home_port,name
0,Tug,266712.0,1976.0,Port of Los Angeles,American Champion
1,Cargo,0.0,0.0,Port of Los Angeles,American Islander
2,Cargo,0.0,0.0,Port of Los Angeles,American Spirit
3,Barge,0.0,2021.0,Port Canaveral,A Shortfall of Gravitas
4,Tug,202302.0,1974.0,Port of Los Angeles,Betty R Gambarella
5,Tug,273063.0,1999.0,Port Canaveral,Elsbeth III
6,High Speed Craft,449964.0,2014.0,Port Canaveral,GO Ms Chief
7,High Speed Craft,449964.0,2015.0,Port Canaveral,GO Ms Tree
8,Cargo,451778.0,2009.0,Port Canaveral,Shannon
9,Cargo,502999.0,2007.0,Port Canaveral,GO Pursuit
10,Cargo,0.0,2014.0,Port Canaveral,GO Quest
11,Cargo,450870.0,2010.0,Port Canaveral,Megan
12,Tug,508023.0,1995.0,Port Canaveral,HAWK
13,Tug,320236.0,1985.0,Fort Lauderdale,Hollywood
14,Barge,0.0,2014.0,Port Canaveral,Just Read The Instructions 1
15,Barge,0.0,2015.0,Port Canaveral,Just Read The Instructions 2
16,Tug,0.0,0.0,Port of Los Angeles,Kelly C
17,Cargo,440892.0,2002.0,Port of Los Angeles,NRC Quest
18,Barge,0.0,2015.0,Port of Los Angeles,Of Course I Still Love You
19,Tug,89811.0,1976.0,Port of Los Angeles,Pacific Freeedom
20,Tug,351080.0,1974.0,Port of Los Angeles,Pacific Warrior
21,Tug,312072.0,1976.0,Port Canaveral,RACHEL
22,Tug,843682.0,1975.0,Port Canaveral,Finn Falgout
23,Tug,741170.0,2003.0,Port Canaveral,Lauren Foss
24,Cargo,2097411.0,2014.0,Port Canaveral,Shelia Bordelon
25,Tug,445428.0,1944.0,Port Canaveral,Mr. Jonah
26,Cargo,4616663.0,2015.0,Port Canaveral,HOS Briarwood
27,Cargo,2719740.0,2009.0,Port Canaveral,Doug
28,Cargo,2719740.0,2009.0,Port Canaveral,Bob

#### 2. Operaciones de strings

Realice las siguientes operaciones en el DataFrame df:

* De la columna home_port extraiga la primera palabra de cada dato y muestre los resultados.
* Determine cuántos datos comienzan con la palabra Port y cuántos
datos comienzan con una palabra diferente, ¿Cuáles son las palabras diferentes?
* Filtre el DataFrame con los datos que en la columna name contengan en el string la palabra “GO” y muestre los resultados.
* Convierta todos los strings de la columna name en palabras con todas sus letras mayúsculas y muestre los resultados.
* Convierta todos los strings de la columna type en palabras con todas sus letras minúsculas y muestre los resultados.
* Divida todos los strings de la columna home_port por el espacio en blanco y muestre los resultados.
* Reemplace todas las palabras ‘Port’ que se encuentran en la columna home_port por la abreviación ‘P.’ y muestre los
resultados.
* Comente todos los procesos realizados y concluya con las posibilidades de uso de estas herramientas en su campo de
acción.

Se utiliza el metodo shape, para determinar la dimensión en columnas y filas del DataFrame, que es una función dentro de la librería Pandas que devuelve el número de filas y columnas de un array.

In [9]:
df1 = df1.shape# se define el dataframe 1
df2 = df2.shape# se define el dataframe 2
print("La dimensión de los DataFrames, se puede observar así:")
print(f"df1: {df1[0]} filas, {df1[1]} columnas")# cero para filas y 1 para columnas
print(f"df2: {df2[0]} filas, {df2[1]} columnas")

La dimensión de los DataFrames, se puede observar así:
df1: 21 filas, 5 columnas
df2: 29 filas, 5 columnas

Se procede con extraer la primera palabra de cada dato en la columna "home_port" y mostrar los resultados, utilizando el método str.split(), éste metodo se utiliza para dividir una columna de cadenas en un DataFrame en función de un delimitador, para después acceder al primer elemento de cada resultado. (Roldán, 2019)

In [10]:
df['first_word'] = df['home_port'].str.split().str[0]#metodo para extraer la primera palabra de la columna
print(df['first_word'])

0     Port
1     Port
2     Port
3     Port
4     Port
5     Port
6     Port
7     Port
8     Port
9     Port
10    Port
11    Port
12    Port
13    Fort
14    Port
15    Port
16    Port
17    Port
18    Port
19    Port
20    Port
21    Port
22    Port
23    Port
24    Port
25    Port
26    Port
27    Port
28    Port
Name: first_word, dtype: object

Se procede hacer  el filtrado de los datos que empienzan con las palabras "port", con palabras diferentes, y la palabra diferente como tal, para este caso, se utiliza el metodo startswith() que utiliza parámetros en: valor, comienzo y fin; es decir si comienza con, en qué posición está y en qué posición está la busqueda. Madhavan (2015)

In [11]:
data_with_port = df[df['home_port'].str.startswith('Port')].shape[0]
data_without_port = df[df['home_port'].str.startswith('Port') == False].shape[0]
different_words = df[df['home_port'].str.startswith('Port') == False]['first_word'].unique()

"""Se utilizó el método str.startswith(), para verificar si una cadena comienza con otra cadena específica. 
    Para este caso, se utiliza en procesamiento de texto y extraer información de las columnas en este la palabra "port" """

print("Cantidad de datos que comienzan con 'Port'es de:", data_with_port)
print("Cantidad de datos que comienzan con una palabra diferente es de:", data_without_port)
print("Palabras diferentes que hay en el DataFrame es :", different_words)

Cantidad de datos que comienzan con 'Port'es de: 28
Cantidad de datos que comienzan con una palabra diferente es de: 1
Palabras diferentes que hay en el DataFrame es : ['Fort']

Filtrar el DataFrame con los datos que en la columna name contengan en el string la palabra “GO” , aplicando el metodo string.contains, que ayuda a filtrar datos, consultandolo en el material de Idris (2024)

In [12]:
df_filtered = df[df['name'].str.contains('GO')]# aplicacion del metodo .str.contains para extraer la palabra GO
df_filtered

,type,mass_kg,year_built,home_port,name,first_word
6,High Speed Craft,449964.0,2014.0,Port Canaveral,GO Ms Chief,Port
7,High Speed Craft,449964.0,2015.0,Port Canaveral,GO Ms Tree,Port
9,Cargo,502999.0,2007.0,Port Canaveral,GO Pursuit,Port
10,Cargo,0.0,2014.0,Port Canaveral,GO Quest,Port

Convertir strings de la columna "name" a mayúsculas utilizando el metodo .str.upper() de la librería Pandas, que sirve para convertir todas las letras minúsculas de una cadena a mayúsculas.

In [13]:
df['name'] = df['name'].str.upper()
print(df['name'])

0                AMERICAN CHAMPION
1                AMERICAN ISLANDER
2                  AMERICAN SPIRIT
3          A SHORTFALL OF GRAVITAS
4               BETTY R GAMBARELLA
5                      ELSBETH III
6                      GO MS CHIEF
7                       GO MS TREE
8                          SHANNON
9                       GO PURSUIT
10                        GO QUEST
11                           MEGAN
12                            HAWK
13                       HOLLYWOOD
14    JUST READ THE INSTRUCTIONS 1
15    JUST READ THE INSTRUCTIONS 2
16                         KELLY C
17                       NRC QUEST
18      OF COURSE I STILL LOVE YOU
19                PACIFIC FREEEDOM
20                 PACIFIC WARRIOR
21                          RACHEL
22                    FINN FALGOUT
23                     LAUREN FOSS
24                 SHELIA BORDELON
25                       MR. JONAH
26                   HOS BRIARWOOD
27                            DOUG
28                             BOB
Name: name, dtype: object

Convertir strings de la columna "type" a minúsculas utilizando el metodo .str.lower(), que sirve para sirve para convertir todas las letras minúsculas de una cadena a mayúsculas. McKinney (2023)

In [14]:
df["type"] = df["type"].str.lower()
print(df["type"])

0                  tug
1                cargo
2                cargo
3                barge
4                  tug
5                  tug
6     high speed craft
7     high speed craft
8                cargo
9                cargo
10               cargo
11               cargo
12                 tug
13                 tug
14               barge
15               barge
16                 tug
17               cargo
18               barge
19                 tug
20                 tug
21                 tug
22                 tug
23                 tug
24               cargo
25                 tug
26               cargo
27               cargo
28               cargo
Name: type, dtype: object

<p style="text-align: justify;">Se procede con dividir todos los strings de la columna home_port por el espacio en blanco utilizando el metodo .str.split() que es un para dividir  las letras de la columna en cadenas de listas con su separador definido, facilitando el análisis y manipulación de texto Madhavan (2015)</p>

In [15]:

df["port_parts"] = df["home_port"].str.split()

print(df[["home_port", "port_parts"]])

              home_port                port_parts
0   Port of Los Angeles  [Port, of, Los, Angeles]
1   Port of Los Angeles  [Port, of, Los, Angeles]
2   Port of Los Angeles  [Port, of, Los, Angeles]
3        Port Canaveral         [Port, Canaveral]
4   Port of Los Angeles  [Port, of, Los, Angeles]
5        Port Canaveral         [Port, Canaveral]
6        Port Canaveral         [Port, Canaveral]
7        Port Canaveral         [Port, Canaveral]
8        Port Canaveral         [Port, Canaveral]
9        Port Canaveral         [Port, Canaveral]
10       Port Canaveral         [Port, Canaveral]
11       Port Canaveral         [Port, Canaveral]
12       Port Canaveral         [Port, Canaveral]
13      Fort Lauderdale        [Fort, Lauderdale]
14       Port Canaveral         [Port, Canaveral]
15       Port Canaveral         [Port, Canaveral]
16  Port of Los Angeles  [Port, of, Los, Angeles]
17  Port of Los Angeles  [Port, of, Los, Angeles]
18  Port of Los Angeles  [Port, of, Los, Angeles]
19  Port of Los Angeles  [Port, of, Los, Angeles]
20  Port of Los Angeles  [Port, of, Los, Angeles]
21       Port Canaveral         [Port, Canaveral]
22       Port Canaveral         [Port, Canaveral]
23       Port Canaveral         [Port, Canaveral]
24       Port Canaveral         [Port, Canaveral]
25       Port Canaveral         [Port, Canaveral]
26       Port Canaveral         [Port, Canaveral]
27       Port Canaveral         [Port, Canaveral]
28       Port Canaveral         [Port, Canaveral]

<p style="text-align: justify;"> Análisis del ejercicio: Desde el campo de mi profesión como profesional en Administración informática y en mis funciones como archivista, estos metodos se pueden utilizar para extraer transformar y cargar en almacenes de datos los registros, para hacer analitica y poder proporcionar a los usuarios internos y externos la información que requieren y coadyuvar en la toma de decisiones en comités de archivo.</p>

<h1><center>CONCLUSION</h1>

<p style="text-align: justify;">La limpieza y el procesamiento de datos son la piedra angular de un análisis de datos sólido y confiable, al abordar los errores, las inconsistencias y la información faltante en los datos brutos, se preparan escenarios para la extracción de conocimientos valiosos y la construcción de modelos de aprendizaje automático precisos; este trabajo ha brindado una introducción fundamental a los conceptos y técnicas clave de limpieza y procesamiento de datos en nuestras labores.</p>

<h1><center>BIBLIOGRAFÍA</h1>

Grus, J. (2023). Ciencia de datos desde cero. Segunda edición: Principios básicos con Python. ANAYA MULTIMEDIA

Idris, I. (2014). Python Data Analysis. Packt Publishing. (pp.131-134).

McKinney, W. (2023). Python para análisis de datos. Comercial Grupo ANAYA, S.A.

Roldán, R. C., Martín, E. M., & Rodríguez, A. R. (2019). Big data con python: Recolección, almacenamiento y proceso. Alpha Editorial.

Samir Madhavan. (2015). Mastering Python for Data Science: Explore the World of Data Science Through Python and Learn How to Make Sense of Data. Packt Publishing. (pp. 11-12).

Zheng, A., & Casari, A. (2018). Feature Engineering for Machine Learning: Principles and Techniques for Data Scientists. «O’Reilly Media, Inc.»